# Generated by Django 4.2.4 on 2023-08-17 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='Description',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30), django.core.validators.MinLengthValidator(2)]),
        ),
    ]
