# Generated by Django 4.2.4 on 2023-08-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_todotask_assignee_alter_todotask_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='IsCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
