# Generated by Django 4.2.4 on 2023-08-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_todotask_iscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='IsCompleted',
            field=models.BooleanField(),
        ),
    ]
