# Generated by Django 4.2.4 on 2023-08-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_todotask_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
